### ISSUE TITLE
Pull Transport Unintialized Audio Recorder

### ISSUE THREAD

**Issue by jpack1337** [kailash09dabhi/OmRecorder#24]
Still receiving this error, even after confirming users have Recording permissions enabled on their device. Seeing issues on 4.4.2 - 7.1 and wanted to reopen this.

```
Fatal Exception: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
       at android.media.AudioRecord.startRecording(AudioRecord.java:894)
       at omrecorder.PullTransport$AbstractPullTransport.preparedSourceToBePulled(PullTransport.java:89)
       at omrecorder.PullTransport$AbstractPullTransport.start(PullTransport.java:70)
       at omrecorder.AbstractRecorder$1.run(AbstractRecorder.java:29)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by nzala** [comment]
[https://developer.android.com/reference/java/lang/IllegalStateException.html](https://developer.android.com/reference/java/lang/IllegalStateException.html)
Signals that a method has been invoked at an illegal or inappropriate time. In other words, the Java environment or Java application is not in an appropriate state for the requested operation.

**Comment by kailash09dabhi** [comment]
@jpack1337 I have already replied to previous issue. The issue is only happens when you fail to release recorder properly. I havent noticed this issue in my personal app too.  Yes but you may have to check that the format you are supplying to OmRecorder should be workable. Some freqency and audioSource may not work with some device and that you have to check on your end.

**Comment by jpack1337** [comment]
Hi @kailash09dabhi , I reached out to you, check your email!

**Comment by kailash09dabhi** [comment]
Closed due to no activity. Please feel yourself free to reopen it.
